// scripts/coimbatore_substitutions.js
// Text, Phrase, Address, and Language substitutions for Kanyakumari -> Coimbatore localization.

const phraseReplacements = [
  // Domains & URLs
  [/https:\/\/servicecenterkanyakumari\.com/g, 'https://servicecentercoimbatore.com'],
  [/servicecenterkanyakumari\.com/g, 'servicecentercoimbatore.com'],
  [/support@servicecenterkanyakumari\.com/g, 'support@servicecentercoimbatore.com'],

  // Filenames & Link paths
  [/ac-repair-service-in-kanyakumari\.html/g, 'ac-repair-service-in-coimbatore.html'],
  [/refrigerator-repair-service-in-kanyakumari\.html/g, 'refrigerator-repair-service-in-coimbatore.html'],
  [/washing-machine-repair-service-in-kanyakumari\.html/g, 'washing-machine-repair-service-in-coimbatore.html'],
  [/tv-repair-service-in-kanyakumari\.html/g, 'tv-repair-service-in-coimbatore.html'],
  [/home-appliance-service-center-kanyakumari\.html/g, 'home-appliance-service-center-coimbatore.html'],
  [/-service-center-kanyakumari\.html/g, '-service-center-coimbatore.html'],
  [/-in-kanyakumari\.html/g, '-in-coimbatore.html'],

  // WhatsApp and Map encodings
  [/%20Kanyakumari\./gi, '%20Coimbatore.'],
  [/%20Kanyakumari/gi, '%20Coimbatore'],
  [/Kanyakumari%2C/gi, 'Coimbatore%2C'],
  [/%2CKanyakumari/gi, '%2CCoimbatore'],
  [/in%20Kanyakumari/gi, 'in%20Coimbatore'],
  [/Court%20Road%20Junction%2C%20Cape%20Road%2C%20Nagercoil%2C%20Kanyakumari%20District%2C%20Tamil%20Nadu%20629001/gi, 'Cross%20Cut%20Road%2C%20Gandhipuram%2C%20Coimbatore%2C%20Tamil%20Nadu%20641012'],

  // Directional Zones
  [/East Kanyakumari/g, 'East Coimbatore'],
  [/West Kanyakumari/g, 'West Coimbatore'],
  [/North Kanyakumari/g, 'North Coimbatore'],
  [/South Kanyakumari/g, 'West Coimbatore'],

  // Addresses & Landmarks
  [/Court Road Junction, Cape Road, Nagercoil, Kanyakumari District, Tamil Nadu 629001/gi, 'Cross Cut Road, Gandhipuram, Coimbatore, Tamil Nadu 641012'],
  [/Court Road Junction, Cape Road, Nagercoil/gi, 'Cross Cut Road, Gandhipuram, Coimbatore'],
  [/3GQX\+RPM, Cape Rd/gi, 'Cross Cut Road, Gandhipuram'],
  [/Near Tower Junction & Cape Road/gi, 'Near Cross Cut Road & Avinashi Road'],
  [/Near Tower Junction/gi, 'Near Gandhipuram Bus Stand'],
  [/Tower Junction/gi, 'Town Hall Clock Tower'],
  [/Vadasery Bus Stand Area/gi, 'Gandhipuram Bus Stand Area'],
  [/Vadasery Bus Stand/gi, 'Gandhipuram Bus Stand'],
  [/Vadasery/gi, 'Gandhipuram'],
  [/Mylaudy, Kottar, Cape Road & all Kanyakumari areas/gi, 'Singanallur, Peelamedu, RS Puram, Saibaba Colony & all Coimbatore areas'],
  [/Mylaudy/gi, 'Singanallur'],
  [/Kottar/gi, 'Ramanathapuram'],
  [/Suchindram/gi, 'Peelamedu'],
  [/Marthandam/gi, 'RS Puram'],
  [/Thuckalay/gi, 'Vadavalli'],
  [/Colachel/gi, 'Saibaba Colony'],
  [/Kulasekharam/gi, 'Thudiyalur'],
  [/Karungal/gi, 'Ganapathy'],
  [/Kuzhithurai/gi, 'Saravanampatti'],
  [/Aralvaimozhi/gi, 'Kavundampalayam'],
  [/Thingalnagar/gi, 'Perur'],
  [/Asaripallam/gi, 'Kovaipudur'],
  [/Ananthanadarkudy/gi, 'Kuniyamuthur'],
  [/Eraniel/gi, 'Sundarapuram'],
  [/Chunkankadai/gi, 'Podanur'],
  [/Konam/gi, 'Kurichi'],
  [/Vettoornimadam/gi, 'Rathinapuri'],
  [/Boothapandi/gi, 'Periyanaickenpalayam'],
  [/Thiruvattar/gi, 'Karamadai'],
  [/Azhagiapandiapuram/gi, 'Annur'],
  [/Carmel Nagar/gi, 'Ram Nagar'],
  [/Agastheeswaram/gi, 'Kalapatti'],
  [/Thamirabarani Road/gi, 'Siruvani Road'],
  [/Thamirabarani river basin/gi, 'Noyyal river basin'],
  [/Thamirabarani river valley/gi, 'Siruvani water zone'],
  [/Thamirabarani river/gi, 'Noyyal river'],
  [/Thamirabarani/gi, 'Siruvani'],
  [/Pazhayar river bridge & residential colony/gi, 'Noyyal river bridge & residential colony'],
  [/Pazhayar river/gi, 'Noyyal river'],
  [/Pazhayar/gi, 'Noyyal'],
  [/Pechiparai canal network area/gi, 'Siruvani pipeline area'],
  [/Pechiparai reservoir/gi, 'Siruvani reservoir'],
  [/Pechiparai canal/gi, 'Siruvani canal'],
  [/Pechiparai/gi, 'Siruvani'],
  [/Cape Road Corridor/gi, 'Avinashi Road Corridor'],
  [/Cape Road Bypass/gi, 'Avinashi Road Bypass'],
  [/Cape Road and Trivandrum Highway/gi, 'Avinashi Road and Mettupalayam Road'],
  [/Cape Road and Court Road/gi, 'Avinashi Road and DB Road'],
  [/Cape Road, WCC Road, Court Road, and Trivandrum Highway/gi, 'Avinashi Road, Cross Cut Road, DB Road, and Trichy Road'],
  [/Cape Road or Court Road/gi, 'Avinashi Road or DB Road'],
  [/along Cape Road and Trivandrum Highway/gi, 'along Avinashi Road and Mettupalayam Road'],
  [/from Cape Road and Court Road/gi, 'from Avinashi Road and DB Road'],
  [/Cape Road/gi, 'Avinashi Road'],
  [/Court Road/gi, 'DB Road'],
  [/WCC Road/gi, 'Cross Cut Road'],
  [/KP Road/gi, 'Trichy Road'],
  [/Trivandrum Highway Road/gi, 'Mettupalayam Road'],
  [/Trivandrum Highway/gi, 'Mettupalayam Road'],
  [/Thanumalayan Temple Suchindram/gi, 'Patteeswarar Temple Perur'],
  [/Thanumalayan Temple/gi, 'Patteeswarar Temple'],
  [/Thanumalayan/gi, 'Patteeswarar'],
  [/Nagercoil Arts & Science College/gi, 'PSG Arts & Science College Coimbatore'],
  [/Collectorate & Court complex area/gi, 'Collectorate & Court complex Coimbatore'],
  [/Collectorate Road Nagercoil/gi, 'Collectorate Road Coimbatore'],
  [/Nagercoil-Cape Corridor/gi, 'Avinashi-Trichy Road Corridor'],
  [/Ponnappa Nadar Nagar/gi, 'Sivananda Colony'],
  [/Simon Nagar/gi, 'Tatabad'],
  [/Christopher Nagar/gi, 'Ram Nagar'],
  [/Vasanth Nagar/gi, 'Rathinapuri'],
  [/NGO Colony Nagercoil/gi, 'Cheran Ma Nagar'],
  [/Putheri/gi, 'Ondipudur'],
  [/Erachakulam/gi, 'Sulur'],
  [/Chenbagaramanputhur/gi, 'Irugur'],
  [/Vellamadam/gi, 'Neelambur'],
  [/Kattathurai/gi, 'Chinniyampalayam'],
  [/Therakalputhur/gi, 'SITRA'],
  [/Kappiyarai/gi, 'Goldwins'],
  [/Helen Nagar/gi, 'Civil Aerodrome'],
  [/Ramavarmapuram/gi, 'KMCH Junction'],
  [/Derik Junction/gi, 'Hope College'],
  [/Muppandal/gi, 'Kalapatti'],
  [/Thittuvilai/gi, 'Cheran Ma Nagar'],
  [/Thadikarankonam/gi, 'Vilankurichi'],
  [/Weavers Colony/gi, 'Sowripalayam'],
  [/Ozhuginasery/gi, 'Udayampalayam'],
  [/Pazhavilai/gi, 'Kallimadai'],
  [/Kaliyakkavilai/gi, 'Neelambur'],

  // Climate and environment terms
  [/humid Kanyakumari coastal conditions/gi, 'warm Coimbatore conditions'],
  [/Kanyakumari coastal conditions/gi, 'Coimbatore climate conditions'],
  [/Kanyakumari coastline/gi, 'Coimbatore region'],
  [/coastal humidity wear/gi, 'dust and temperature wear'],
  [/coastal humidity/gi, 'seasonal heat and fine dust'],
  [/coastal weather/gi, 'outdoor weather'],
  [/coastal salt air/gi, 'fine industrial dust'],
  [/coastal conditions/gi, 'local climate conditions'],
  [/Kanyakumari climate/gi, 'Coimbatore climate'],
  [/Kanyakumari water conditions/gi, 'Coimbatore borewell and Siruvani water conditions'],
  [/Kanyakumari water/gi, 'Coimbatore water'],

  // City names and Brand names
  [/\bService Center Kanyakumari\b/g, 'Service Center Coimbatore'],
  [/\bSERVICE CENTER KANYAKUMARI\b/g, 'SERVICE CENTER COIMBATORE'],
  [/\bservice center kanyakumari\b/g, 'service center coimbatore'],
  [/\bKanyakumari District\b/g, 'Coimbatore District'],
  [/\bKanyakumari district\b/g, 'Coimbatore district'],
  [/\bKanniyakumari District\b/g, 'Coimbatore District'],
  [/\bKanniyakumari district\b/g, 'Coimbatore district'],
  [/\bNagercoil Town\b/g, 'Gandhipuram'],
  [/\bNagercoil town\b/g, 'Gandhipuram'],
  [/\bNagercoil\b/g, 'Coimbatore'],
  [/\bKanniyakumari\b/g, 'Coimbatore'],
  [/\bkanniyakumari\b/g, 'coimbatore'],
  [/\bKanyakumari\b/g, 'Coimbatore'],
  [/\bkanyakumari\b/g, 'coimbatore'],

  // Simple Human Indian English substitutions
  [/\bprompt assistance\b/gi, 'quick help'],
  [/\bcomprehensive assistance\b/gi, 'complete help'],
  [/\bdedicated service desk\b/gi, 'local service team'],
  [/\bcustomer support desk\b/gi, 'customer support'],
  [/\bservice desk\b/gi, 'service center'],
  [/\bfacilitate\b/gi, 'help'],
  [/\bcommence service\b/gi, 'start the service'],
  [/\bcommence\b/gi, 'start'],
  [/\bresidential premises\b/gi, 'home'],
  [/\bpremises\b/gi, 'home'],
  [/\btechnical intervention\b/gi, 'repair work'],
  [/\bpromptly\b/gi, 'quickly'],
  [/\butilize\b/gi, 'use'],
  [/\bdiagnostic assessment\b/gi, 'checking'],
  [/\bmalfunctioning\b/gi, 'not working properly'],
  [/\brectification\b/gi, 'repair'],
  [/\bexpeditious\b/gi, 'quick'],
  [/\bendeavour\b/gi, 'try'],
  [/\bprovision of services\b/gi, 'service'],
  [/\bseamless service experience\b/gi, 'smooth repair visit'],
  [/\btailored solutions\b/gi, 'correct fixes'],
  [/\bdedicated service support\b/gi, 'dependable service help'],
  [/\bexpert technical intervention\b/gi, 'skilled repair work'],
  [/\breliable and professional service\b/gi, 'honest and quick service'],
  [/\bcomprehensive appliance solutions\b/gi, 'complete appliance repairs']
];

function applySubstitutions(content) {
  let c = content;
  for (const [regex, replacement] of phraseReplacements) {
    c = c.replace(regex, replacement);
  }
  return c;
}

module.exports = {
  applySubstitutions,
  phraseReplacements
};
