// 150 Verified Coimbatore District Localities Directional Master List
// 50 East Coimbatore, 50 West Coimbatore, 50 North Coimbatore = 150 Total Unique Entries.

module.exports = {
  east: [
    { name: "Singanallur", landmark: "Trichy Road junction & central bus terminus", pincode: "641005" },
    { name: "Peelamedu", landmark: "PSG Tech campus & Avinashi Road hub", pincode: "641004" },
    { name: "Ramanathapuram", landmark: "Trichy Road retail corridor & residential layout", pincode: "641045" },
    { name: "Hope College", landmark: "Avinashi Road junction & student housing", pincode: "641004" },
    { name: "Ondipudur", landmark: "Trichy Road flyover & residential layouts", pincode: "641016" },
    { name: "Sulur", landmark: "Air Force station town & lake promenade", pincode: "641402" },
    { name: "Irugur", landmark: "Railway feeder road & family housing colonies", pincode: "641103" },
    { name: "Hopes", landmark: "Commercial intersection & residential avenues", pincode: "641004" },
    { name: "Varadharajapuram", landmark: "Sowripalayam link & housing societies", pincode: "641015" },
    { name: "Sowripalayam", landmark: "Meena Estate & residential neighborhoods", pincode: "641028" },
    { name: "Udayampalayam", landmark: "Nava India link road & apartment complexes", pincode: "641028" },
    { name: "Kallimadai", landmark: "Trichy Road bypass & family housing", pincode: "641005" },
    { name: "Neelambur", landmark: "Avinashi bypass toll & engineering college belt", pincode: "641062" },
    { name: "Chinniyampalayam", landmark: "Airport approach road & logistics colony", pincode: "641062" },
    { name: "Civil Aerodrome", landmark: "Coimbatore Airport residential quarters", pincode: "641014" },
    { name: "SITRA", landmark: "Airport junction & Avinashi Road residences", pincode: "641014" },
    { name: "Goldwins", landmark: "Avinashi Road educational corridor", pincode: "641014" },
    { name: "KMCH Junction", landmark: "Super-specialty hospital perimeter & flats", pincode: "641014" },
    { name: "Chitra Nagar", landmark: "Aerodrome road residential streets", pincode: "641014" },
    { name: "Kalapatti", landmark: "IT park link road & gated villa layouts", pincode: "641048" },
    { name: "Thottipalayam", landmark: "Avinashi Road link & quiet residential homes", pincode: "641062" },
    { name: "Ravathur", landmark: "Irugur-Sulur rural belt & family dwellings", pincode: "641103" },
    { name: "Pallapalayam", landmark: "Town panchayat streets & residential colonies", pincode: "641103" },
    { name: "Kannampalayam", landmark: "Sulur link road & agricultural-residential belt", pincode: "641402" },
    { name: "Kangayampalayam", landmark: "Trichy Road township & housing enclaves", pincode: "641401" },
    { name: "Ranganathapuram", landmark: "Sulur lake perimeter & residential quarters", pincode: "641402" },
    { name: "Pattanam", landmark: "Ondipudur bypass & quiet suburban homes", pincode: "641016" },
    { name: "Vellalore", landmark: "Bus terminus development & housing board colony", pincode: "641111" },
    { name: "Konavaayanpalayam", landmark: "Noyyal riverbank link & suburban homes", pincode: "641111" },
    { name: "Nanjundapuram", landmark: "Ittige Koodu road & riverbank apartment belt", pincode: "641036" },
    { name: "Parsn Sesh Nestale", landmark: "Nanjundapuram gated residential township", pincode: "641036" },
    { name: "Puliakulam", landmark: "Mundhi Vinayagar temple square & family homes", pincode: "641045" },
    { name: "Pankaja Mills Road", landmark: "Ramanathapuram link & residential lanes", pincode: "641045" },
    { name: "Trichy Road", landmark: "Arterial east-bound highway & commercial avenue", pincode: "641018" },
    { name: "Stock Exchange Road", landmark: "Singanallur corporate & residential belt", pincode: "641005" },
    { name: "Masakalipalayam", landmark: "Hope College-Sowripalayam residential cross", pincode: "641015" },
    { name: "Krishnarayapuram (Peelamedu)", landmark: "Foundry belt & family residences", pincode: "641004" },
    { name: "PSG Estate", landmark: "Peelamedu staff & student residential layout", pincode: "641004" },
    { name: "Codissia Road", landmark: "Trade fair complex link & housing colonies", pincode: "641014" },
    { name: "Nehru Nagar (Kalapatti)", landmark: "Airport link road & modern villas", pincode: "641014" },
    { name: "Sharp Nagar", landmark: "Kalapatti industrial & residential neighborhood", pincode: "641048" },
    { name: "Cheran Ma Nagar", landmark: "Housing unit colony & bus terminus layout", pincode: "641035" },
    { name: "Vilankurichi", landmark: "Tidel Park IT corridor & residential apartments", pincode: "641035" },
    { name: "Tidel Park Area", landmark: "Tech park perimeter & corporate apartments", pincode: "641014" },
    { name: "Nava India", landmark: "Avinashi Road flyover & college junction", pincode: "641004" },
    { name: "Perks School Road", landmark: "Uppilipalayam link & peaceful residences", pincode: "641015" },
    { name: "Uppilipalayam", landmark: "Singanallur railway link & colony streets", pincode: "641015" },
    { name: "Meena Estate", landmark: "Sowripalayam residential layout & avenues", pincode: "641028" },
    { name: "Kamaraj Road", landmark: "Singanallur-Hopes link & retail cross roads", pincode: "641015" },
    { name: "Eachanari", landmark: "Temple junction & industrial-residential corridor", pincode: "641021" }
  ],
  west: [
    { name: "RS Puram", landmark: "DB Road commercial boulevard & prime residences", pincode: "641002" },
    { name: "Vadavalli", landmark: "Marudhamalai foothills & premier residential hub", pincode: "641041" },
    { name: "Veerakeralam", landmark: "Vadavalli-Perur link road & quiet garden layouts", pincode: "641007" },
    { name: "Thondamuthur", landmark: "Agricultural foothill valley & town bazaar", pincode: "641109" },
    { name: "Perur", landmark: "Historic Patteeswarar temple car street & Noyyal banks", pincode: "641010" },
    { name: "Telungupalayam", landmark: "Siruvani Road residential colony & weavers lane", pincode: "641039" },
    { name: "Selvapuram", landmark: "Perur main road & traditional residential streets", pincode: "641026" },
    { name: "Kovaipudur", landmark: "Scenic hill-view township & quiet residential colony", pincode: "641042" },
    { name: "Kuniyamuthur", landmark: "Palakkad Road arterial junction & college belt", pincode: "641008" },
    { name: "Sundarapuram", landmark: "Pollachi Road commercial market & residential hub", pincode: "641024" },
    { name: "Kurichi", landmark: "Housing unit layout & manufacturing workshops", pincode: "641024" },
    { name: "Podanur", landmark: "Historic railway junction colony & shaded avenues", pincode: "641023" },
    { name: "Chettipalayam Road", landmark: "Podanur link & suburban housing plots", pincode: "641023" },
    { name: "Madukkarai", landmark: "Cement factory town & NH544 junction", pincode: "641105" },
    { name: "Maruthamalai Road", landmark: "Temple approach avenue & university belt", pincode: "641046" },
    { name: "Bharathiar University Area", landmark: "Academic campus perimeter & faculty homes", pincode: "641046" },
    { name: "Somayampalayam", landmark: "Foothill residential layouts & student rooms", pincode: "641046" },
    { name: "Kalveerampalayam", landmark: "Maruthamalai main road & peaceful residences", pincode: "641046" },
    { name: "Navavoor Pirivu", landmark: "Vadavalli extension & modern villa layouts", pincode: "641046" },
    { name: "IOB Colony", landmark: "Maruthamalai road established family layout", pincode: "641046" },
    { name: "Bommanampalayam", landmark: "Mountain backdrop & farmhouse community", pincode: "641112" },
    { name: "Vedapatti", landmark: "Noyyal river canal road & fertile residential village", pincode: "641007" },
    { name: "Alandurai", landmark: "Siruvani foothills & western highway trade center", pincode: "641101" },
    { name: "Pooluvapatti", landmark: "Siruvani main road town panchayat & market", pincode: "641101" },
    { name: "Thenkarai", landmark: "Western Ghats foothill village & rural residences", pincode: "641101" },
    { name: "Semmedu", landmark: "Siruvani road & agricultural family households", pincode: "641114" },
    { name: "Iruttupallam", landmark: "Isha road junction & scenic foothill residences", pincode: "641114" },
    { name: "Gandhipark", landmark: "Historic west-central park square & retail shops", pincode: "641001" },
    { name: "Sukrawarpet", landmark: "Traditional jewelers street & bustling commerce", pincode: "641001" },
    { name: "Town Hall", landmark: "Clock tower circle & heritage wholesale bazaar", pincode: "641001" },
    { name: "Oppanakara Street", landmark: "Central textile market & commercial artery", pincode: "641001" },
    { name: "Raja Street", landmark: "Koniamman temple square & heritage shopping lanes", pincode: "641001" },
    { name: "Big Bazaar Street", landmark: "Historic trade hub & traditional homes", pincode: "641001" },
    { name: "Vysial Street", landmark: "Heritage merchant quarter & quiet family cross-lanes", pincode: "641001" },
    { name: "Sullivan Street", landmark: "Historic downtown residential & business road", pincode: "641001" },
    { name: "DB Road", landmark: "Diwan Bahadur road shopping & dining corridor", pincode: "641002" },
    { name: "TVS Nagar", landmark: "Thadagam road link & peaceful residential colony", pincode: "641025" },
    { name: "Koundampalayam West", landmark: "Edayarpalayam link road & housing layouts", pincode: "641030" },
    { name: "Edayarpalayam", landmark: "Thadagam road junction & dense residential hub", pincode: "641025" },
    { name: "Vadavalli Road", landmark: "RS Puram to Vadavalli transit & shopping avenue", pincode: "641041" },
    { name: "Shastri Maidan", landmark: "RS Puram community playground & family streets", pincode: "641002" },
    { name: "Cowley Brown Road", landmark: "Forest College perimeter & quiet tree-lined homes", pincode: "641002" },
    { name: "Lawley Road", landmark: "TNAU Agricultural University junction & staff flats", pincode: "641003" },
    { name: "TNAU Campus", landmark: "Green botanical campus perimeter & faculty quarters", pincode: "641003" },
    { name: "Forest College Area", landmark: "Silviculture campus link & residential avenues", pincode: "641043" },
    { name: "Seeranaickenpalayam", landmark: "Agricultural college perimeter & quiet colony", pincode: "641007" },
    { name: "Poomarket", landmark: "Historic wholesale flower market & commercial street", pincode: "641001" },
    { name: "Karumbukadai", landmark: "Ukkadam lake perimeter & residential settlement", pincode: "641008" },
    { name: "Ukkadam", landmark: "Bus terminal hub & Periyakulam lakefront promenade", pincode: "641001" },
    { name: "Kovaipudur Pirivu", landmark: "Palakkad Road turnoff & suburban expansion", pincode: "641008" }
  ],
  north: [
    { name: "Saibaba Colony", landmark: "NSR Road upscale retail & residential haven", pincode: "641011" },
    { name: "NSR Road", landmark: "Saibaba Colony prime commercial avenue & apartments", pincode: "641011" },
    { name: "Ganapathy", landmark: "Sathy Road industrial hub & extensive residential zones", pincode: "641006" },
    { name: "Saravanampatti", landmark: "IT corridor, Chil Sez tech park & modern flats", pincode: "641035" },
    { name: "Thudiyalur", landmark: "Mettupalayam Road transit hub & family layouts", pincode: "641034" },
    { name: "Kavundampalayam", landmark: "Mettupalayam Road flyover & bustling markets", pincode: "641030" },
    { name: "Gandhipuram", landmark: "Central bus terminal, Cross Cut Road retail hub", pincode: "641012" },
    { name: "Cross Cut Road", landmark: "Premier shopping boulevard & electronics market", pincode: "641012" },
    { name: "100 Feet Road", landmark: "Commercial showroom corridor & central retail", pincode: "641012" },
    { name: "Ram Nagar", landmark: "Gandhipuram adjacent quiet residential neighborhood", pincode: "641009" },
    { name: "Tatabad", landmark: "Power house road & established family layout", pincode: "641012" },
    { name: "Sivananda Colony", landmark: "Hudco colony link & serene residential streets", pincode: "641012" },
    { name: "Rathinapuri", landmark: "Sathy road feeder & dense residential neighborhood", pincode: "641027" },
    { name: "Sanganoor", landmark: "Industrial workshops & residential cross streets", pincode: "641027" },
    { name: "Kannappa Nagar", landmark: "Sanganoor link & quiet suburban housing", pincode: "641027" },
    { name: "Maniyakarampalayam", landmark: "Ganapathy expansion & modern apartments", pincode: "641006" },
    { name: "Awarampalayam", landmark: "Foundry belt & quiet family residential lanes", pincode: "641006" },
    { name: "Peelamedu Pudur", landmark: "North Peelamedu link & residential avenues", pincode: "641004" },
    { name: "Bharathi Nagar (Ganapathy)", landmark: "Sathy Road residential colony & school street", pincode: "641006" },
    { name: "Urumandampalayam", landmark: "Thudiyalur link & new residential layouts", pincode: "641034" },
    { name: "Vellakinar", landmark: "IT park proximity & housing board colony", pincode: "641029" },
    { name: "GN Mills", landmark: "Mettupalayam road textile mill perimeter & homes", pincode: "641029" },
    { name: "Subramaniapalayam", landmark: "GN Mills link road & quiet residential streets", pincode: "641029" },
    { name: "Vadamadurai", landmark: "Mettupalayam Road temple stop & residential villas", pincode: "641017" },
    { name: "Periyanaickenpalayam", landmark: "LMW industrial hub & established township", pincode: "641020" },
    { name: "Naickenpalayam", landmark: "Mettupalayam Road foothill link & residences", pincode: "641020" },
    { name: "Gudalur (Coimbatore North)", landmark: "Town panchayat streets & mountain view homes", pincode: "641020" },
    { name: "Samichettipalayam", landmark: "Jothipuram link & suburban family residences", pincode: "641047" },
    { name: "Jothipuram", landmark: "Industrial township & Mettupalayam road settlement", pincode: "641047" },
    { name: "Veerapandi", landmark: "Press colony perimeter & quiet residential plots", pincode: "641019" },
    { name: "Press Colony", landmark: "Government press township & family housing", pincode: "641019" },
    { name: "Karamadai", landmark: "Ranganathar temple town & railway junction area", pincode: "641104" },
    { name: "Mettupalayam Road", landmark: "Major north-bound highway & retail auto hub", pincode: "641030" },
    { name: "Sathy Road", landmark: "Arterial IT & educational highway corridor", pincode: "641035" },
    { name: "CHIL SEZ IT Park", landmark: "Saravanampatti tech campus & luxury apartments", pincode: "641035" },
    { name: "Keeranatham", landmark: "SEZ tech zone link & fast-growing gated colonies", pincode: "641035" },
    { name: "Idikarai", landmark: "Historic town panchayat & serene countryside houses", pincode: "641022" },
    { name: "Athipalayam", landmark: "Sathy road link & agricultural-residential belt", pincode: "641110" },
    { name: "Kovilpalayam", landmark: "Kousika river bridge & Sathy Road highway town", pincode: "641107" },
    { name: "Sarkarsamakulam", landmark: "Panchayat union center & quiet village residences", pincode: "641107" },
    { name: "Kunnathur", landmark: "Kovilpalayam suburban link & farm homes", pincode: "641107" },
    { name: "Kurumbapalayam", landmark: "Sathy Road educational zone & family residences", pincode: "641107" },
    { name: "Annur", landmark: "Major north-east junction town & textile trading center", pincode: "641653" },
    { name: "Pasur (Annur)", landmark: "Quiet rural-residential neighborhood", pincode: "641653" },
    { name: "Kondayampalayam", landmark: "Saravanampatti extension & new villa projects", pincode: "641110" },
    { name: "Chinna Vedampatti", landmark: "College link road & residential layouts", pincode: "641049" },
    { name: "Periya Vedampatti", landmark: "Agricultural perimeter & serene family houses", pincode: "641049" },
    { name: "Anjugam Nagar", landmark: "Vedampatti link & affordable housing colony", pincode: "641049" },
    { name: "Lakshmi Nagar (Thudiyalur)", landmark: "Mettupalayam road residential enclave", pincode: "641034" },
    { name: "Pannimadai", landmark: "Western Ghats northern foothill village & farm houses", pincode: "641017" }
  ]
};
