// scripts/erode_localities.js
// Master List of 200 Erode Localities: 50 East, 50 West, 50 North, 50 South
// All verified localities, residential colonies, commercial corridors, and municipal wards in Erode District.

module.exports = {
  east: [
    { name: "Karungalpalayam", landmark: "Cauvery River Bridge", pincode: "638003" },
    { name: "Cauvery Road", landmark: "Water Works Office", pincode: "638003" },
    { name: "Pallipalayam", landmark: "Cauvery River Crossing", pincode: "638006" },
    { name: "Agraharam", landmark: "Periya Agraharam East", pincode: "638005" },
    { name: "Vairapalayam", landmark: "Near Vairapalayam Checkpost", pincode: "638003" },
    { name: "Krishna Theatre Road", landmark: "Near East Market", pincode: "638001" },
    { name: "Manikoondu", landmark: "Clock Tower Roundabout", pincode: "638001" },
    { name: "R.K.V. Road", landmark: "Radhakrishnan Street Textile Shops", pincode: "638001" },
    { name: "Eswaran Kovil Street", landmark: "Arulmigu Eswaran Temple", pincode: "638001" },
    { name: "Marapalam", landmark: "Kalingarayan Canal Bridge", pincode: "638001" },
    { name: "Kamaraj High Road", landmark: "Kamaraj Statue Junction", pincode: "638001" },
    { name: "Netaji Road", landmark: "East Commercial Strip", pincode: "638001" },
    { name: "Old Bus Stand Area", landmark: "Near Town Hall", pincode: "638001" },
    { name: "Brough Road East", landmark: "Near CSI Church", pincode: "638001" },
    { name: "Gandhiji Road", landmark: "East Town Market", pincode: "638001" },
    { name: "PS Park", landmark: "Panneerselvam Park Junction", pincode: "638001" },
    { name: "Kalaimagal Kalvi Nilayam Road", landmark: "Near School Campus", pincode: "638001" },
    { name: "Erode Fort", landmark: "Historic Kottai Area", pincode: "638001" },
    { name: "Kottai Eswaran Koil", landmark: "Kottai Temple Street", pincode: "638001" },
    { name: "Kottai Perumal Kovil", landmark: "Perumal Temple Street", pincode: "638001" },
    { name: "Cutchery Street", landmark: "Old Taluk Office Road", pincode: "638001" },
    { name: "Meenatchi Sundaranar Road", landmark: "East Commercial Complex", pincode: "638001" },
    { name: "Mosikeeranar Street", landmark: "Near Head Post Office", pincode: "638001" },
    { name: "EVN Road", landmark: "E.V.Narasimhan Street", pincode: "638001" },
    { name: "Nachiappa Street", landmark: "Textile Market Road", pincode: "638001" },
    { name: "Park Road", landmark: "Opposite VOC Park Gates", pincode: "638003" },
    { name: "Kongu Nagar East", landmark: "East Colony Main", pincode: "638003" },
    { name: "SPB Colony", landmark: "Paper Mill Township East", pincode: "638010" },
    { name: "Alampalayam", landmark: "East Cauvery Bank", pincode: "638008" },
    { name: "Kokkarayanpettai", landmark: "River Canal Road", pincode: "638007" },
    { name: "Kumarapalayam Road", landmark: "East Link Highway", pincode: "638183" },
    { name: "Solar Pudur", landmark: "East Solar Extension", pincode: "638002" },
    { name: "Lakkapuram East", landmark: "East Ring Road", pincode: "638002" },
    { name: "Karumandisellipalayam East", landmark: "East Rural Outskirts", pincode: "638052" },
    { name: "Vendipalayam Barrage Road", landmark: "Cauvery Barrage View", pincode: "638002" },
    { name: "Chidambaram Colony East", landmark: "Near East Canal", pincode: "638001" },
    { name: "Nadarmedu East", landmark: "Near Nadarmedu Market", pincode: "638002" },
    { name: "Shanthi Nagar", landmark: "Near Karungalpalayam School", pincode: "638003" },
    { name: "Anna Statue Junction", landmark: "East City Entrance", pincode: "638001" },
    { name: "Nanjappa School Road", landmark: "Near Nanjappa Grounds", pincode: "638001" },
    { name: "New Cinema Road", landmark: "Near Royal Theatre", pincode: "638001" },
    { name: "Agilmedu Street", landmark: "Near 6th Cross", pincode: "638001" },
    { name: "Chinnasamy Street", landmark: "Textile Godown Row", pincode: "638001" },
    { name: "VOC Street", landmark: "East Market Extension", pincode: "638001" },
    { name: "Periyar Street", landmark: "Near East Bus Stop", pincode: "638001" },
    { name: "Weavers Colony", landmark: "Handloom Weavers Enclave", pincode: "638003" },
    { name: "Telephone Nagar", landmark: "Near BSNL Office East", pincode: "638001" },
    { name: "VOC Market Road", landmark: "Vegetable Wholesale Market", pincode: "638001" },
    { name: "Cauvery Nagar", landmark: "Riverfront Residential Street", pincode: "638003" },
    { name: "Ashokapuram East", landmark: "Near Power Grid Station", pincode: "638003" }
  ],

  west: [
    { name: "Thindal", landmark: "Near Thindal Murugan Hill Temple", pincode: "638012" },
    { name: "Thindal Murugan Kovil Area", landmark: "Temple Arch Junction", pincode: "638012" },
    { name: "Thindal Medu", landmark: "Thindal High Grounds", pincode: "638012" },
    { name: "Perundurai Road", landmark: "Main Western Arterial Road", pincode: "638011" },
    { name: "Sampath Nagar", landmark: "Near Housing Board Colony", pincode: "638011" },
    { name: "Teachers Colony", landmark: "Near Community Hall", pincode: "638011" },
    { name: "New Teachers Colony", landmark: "Opposite Collectorate Camp", pincode: "638011" },
    { name: "Kumalan Kuttai", landmark: "Near Water Tank", pincode: "638011" },
    { name: "Edayankattuvalasu", landmark: "Near Mettur Road Western End", pincode: "638011" },
    { name: "Collectorate Area", landmark: "District Administrative Complex", pincode: "638011" },
    { name: "Nasiyanur", landmark: "Nasiyanur Panchayat Junction", pincode: "638107" },
    { name: "Nasiyanur Road", landmark: "Four Roads Crossing", pincode: "638011" },
    { name: "Villarasampatti", landmark: "Near Lake Road", pincode: "638107" },
    { name: "Villarasampatti Four Roads", landmark: "Western Bypass Ring", pincode: "638107" },
    { name: "Pavalathampalayam", landmark: "Near Kongu Polytechnic Road", pincode: "638012" },
    { name: "Koorapalayam", landmark: "Ring Road Intersection", pincode: "638052" },
    { name: "Sengodampalayam", landmark: "Near Thindal West", pincode: "638012" },
    { name: "Moolakkarai", landmark: "Near Nasiyanur Link", pincode: "638107" },
    { name: "Palayapalayam", landmark: "Near Palayapalayam Bus Stop", pincode: "638011" },
    { name: "Sakthi Nagar Thindal", landmark: "Residential Layout Phase 2", pincode: "638012" },
    { name: "Sudha Hospital Road", landmark: "Hospital Lane", pincode: "638011" },
    { name: "Rajaswamy Nagar", landmark: "Behind Collectorate", pincode: "638011" },
    { name: "NGO Colony Thindal", landmark: "Government Employees Enclave", pincode: "638012" },
    { name: "Maruthi Nagar", landmark: "Near Thindal Bypass", pincode: "638012" },
    { name: "Golden City Thindal", landmark: "Gated Community Enclave", pincode: "638012" },
    { name: "Indira Nagar", landmark: "Near Western Overbridge", pincode: "638011" },
    { name: "Texvalley Surroundings", landmark: "Gangapuram Textile Mall", pincode: "638102" },
    { name: "Veppampalayam", landmark: "Near Veppampalayam Checkpost", pincode: "638107" },
    { name: "Kaspapet", landmark: "Near West Link Road", pincode: "638115" },
    { name: "Vettukattuvalasu", landmark: "Near Palayapalayam Cross", pincode: "638011" },
    { name: "Bharathi Nagar", landmark: "Near Teachers Colony West", pincode: "638011" },
    { name: "SBI Colony", landmark: "Near Perundurai Road Canara Bank", pincode: "638011" },
    { name: "LIC Colony Thindal", landmark: "Opposite Kongu Arts College", pincode: "638012" },
    { name: "Rayapalayam Pudur", landmark: "Near Western Canal", pincode: "638052" },
    { name: "Gangapuram West", landmark: "Near NH544 Highway", pincode: "638102" },
    { name: "Chithode Bypass West", landmark: "National Highway Flyover", pincode: "638102" },
    { name: "Mettukadai", landmark: "Perundurai Highway Stop", pincode: "638107" },
    { name: "Perundurai SIPCOT", landmark: "Industrial Township Gate", pincode: "638052" },
    { name: "Perundurai Old Bus Stand", landmark: "Town Bus Stand Square", pincode: "638052" },
    { name: "Perundurai RS", landmark: "Railway Station Road", pincode: "638052" },
    { name: "Chennimalai Road West", landmark: "Link to Railway Colony", pincode: "638009" },
    { name: "Sanitorium Area Perundurai", landmark: "Government Hospital Road", pincode: "638053" },
    { name: "Kamban Nagar", landmark: "Near Thindal Medu", pincode: "638012" },
    { name: "Sri Nagar Thindal", landmark: "Near Vasavi School", pincode: "638012" },
    { name: "Thiruvalluvar Nagar", landmark: "Near Kumalan Kuttai Park", pincode: "638011" },
    { name: "VOC Nagar West", landmark: "Near Sampath Nagar Main", pincode: "638011" },
    { name: "Jaganathan Nagar", landmark: "Opposite Sudha Hospital", pincode: "638011" },
    { name: "Royal City", landmark: "Behind Kongu Arts Campus", pincode: "638012" },
    { name: "Thirunagar Colony West", landmark: "Near Municipal School", pincode: "638011" },
    { name: "Annamalai Layout", landmark: "Near Nasiyanur Link Road", pincode: "638011" }
  ],

  north: [
    { name: "Veerappanchatram", landmark: "Near Mariamman Temple", pincode: "638004" },
    { name: "Periyasemur", landmark: "Near Sathy Road Junction", pincode: "638004" },
    { name: "B.P. Agraharam", landmark: "Brahmana Periya Agraharam Main", pincode: "638005" },
    { name: "Sathy Road", landmark: "Sathyamangalam Highway Corridor", pincode: "638004" },
    { name: "Chithode", landmark: "Four Roads Flyover Junction", pincode: "638102" },
    { name: "Bhavani", landmark: "Sangameshwarar Temple City", pincode: "638301" },
    { name: "Bhavani Kooduthurai", landmark: "Triveni Sangam River Ghat", pincode: "638301" },
    { name: "Suriyampalayam", landmark: "Near Corporation Zone 1 Office", pincode: "638005" },
    { name: "Lakshmi Nagar Chithode", landmark: "Near Textile Processing Park", pincode: "638316" },
    { name: "Mettur Road North", landmark: "Near Swastik Roundana", pincode: "638011" },
    { name: "R.N. Pudur", landmark: "Bhavani Main Road", pincode: "638005" },
    { name: "Kaniravutharkulam", landmark: "Near Municipal Lake Park", pincode: "638004" },
    { name: "Kalingarayanpalayam", landmark: "Canal Regulator Point", pincode: "638301" },
    { name: "Urachikottai", landmark: "Near Bhavani Water Treatment Plant", pincode: "638301" },
    { name: "Anthiyur Road Junction", landmark: "Bhavani North Bypass", pincode: "638301" },
    { name: "Odathurai", landmark: "Near River Ferry Point", pincode: "638316" },
    { name: "Periyapuliyur", landmark: "Near Bhavani River Bank", pincode: "638455" },
    { name: "Vasavi College Area", landmark: "Near Vasavi College Campus", pincode: "638316" },
    { name: "Ellapalayam", landmark: "Near North Water Tank", pincode: "638004" },
    { name: "Mettunasuvampalayam", landmark: "Sathy Highway Link", pincode: "638301" },
    { name: "Perumalmalai", landmark: "Hill Temple Foothills", pincode: "638316" },
    { name: "Chithode Four Roads", landmark: "NH544 Crossing", pincode: "638102" },
    { name: "Kumilamparappu", landmark: "Near North Bypass Ring", pincode: "638102" },
    { name: "Muniappan Kovil Street", landmark: "Veerappanchatram North", pincode: "638004" },
    { name: "Manickampalayam", landmark: "Housing Unit Block", pincode: "638004" },
    { name: "Housing Unit Veerappanchatram", landmark: "TNHB Complex", pincode: "638004" },
    { name: "Nalligoundenpalayam", landmark: "Near North Textile Mills", pincode: "638102" },
    { name: "Kanirowther Kulam", landmark: "Near Sathy Road Overbridge", pincode: "638004" },
    { name: "Cauvery RS North", landmark: "Near North Goods Yard", pincode: "638007" },
    { name: "V.Chatram Main Road", landmark: "Textile Market Corridor", pincode: "638004" },
    { name: "GH Roundana North", landmark: "District Headquarters Hospital", pincode: "638009" },
    { name: "Swastik Roundana", landmark: "Central Bus Route Junction", pincode: "638001" },
    { name: "Railway Colony North", landmark: "Near North Rail Gates", pincode: "638002" },
    { name: "Gandhiji Road North", landmark: "Old Municipal Limit", pincode: "638001" },
    { name: "Chettipalayam North", landmark: "Near Sathy Link Road", pincode: "638004" },
    { name: "Sundaram Street", landmark: "Near Periyasemur Market", pincode: "638004" },
    { name: "VOC Nagar Veerappanchatram", landmark: "Behind Mariamman Kovil", pincode: "638004" },
    { name: "Anna Nagar Veerappanchatram", landmark: "Residential Layout Phase 1", pincode: "638004" },
    { name: "Periyar Nagar North", landmark: "Near Periyar Community Hall", pincode: "638001" },
    { name: "Semur Post Office Road", landmark: "Periyasemur Post Office", pincode: "638004" },
    { name: "Kongu Arts College Road", landmark: "College Approach Road", pincode: "638107" },
    { name: "Elavamalai", landmark: "Near NH Highway Outpost", pincode: "638316" },
    { name: "Konalai Road", landmark: "Near Rural North Link", pincode: "638301" },
    { name: "Bhavanisagar Road Junction", landmark: "North Highway Divergence", pincode: "638451" },
    { name: "Salangapalayam", landmark: "Agricultural Market Centre", pincode: "638455" },
    { name: "Kavindapadi Road Junction", landmark: "Sugar Mill Highway Link", pincode: "638455" },
    { name: "Appakudal Road", landmark: "North Industrial Corridor", pincode: "638315" },
    { name: "Kuruppanaickenpalayam", landmark: "Near Cauvery Riverbed", pincode: "638301" },
    { name: "Komarapalayam Bypass", landmark: "Cauvery North Bridge", pincode: "638183" },
    { name: "Alukuli Road", landmark: "North Farm Ring Road", pincode: "638453" }
  ],

  south: [
    { name: "Surampatti", landmark: "Near Surampatti Bus Terminal", pincode: "638009" },
    { name: "Surampatti Valasu", landmark: "Valasu Mariamman Temple", pincode: "638009" },
    { name: "Surampatti Four Roads", landmark: "Key Southern Commercial Cross", pincode: "638009" },
    { name: "Kasipalayam", landmark: "Near Kasipalayam Municipal Office", pincode: "638009" },
    { name: "Kollampalayam", landmark: "Near Railway Overbridge", pincode: "638002" },
    { name: "Moolapalayam", landmark: "Near Karur Main Road Junction", pincode: "638002" },
    { name: "Solar", landmark: "Solar New Bus Stand Corridor", pincode: "638002" },
    { name: "Solar New Bus Stand", landmark: "Mofussil Integrated Bus Terminal", pincode: "638002" },
    { name: "Erode Railway Junction Area", landmark: "Central Railway Station", pincode: "638002" },
    { name: "Chennimalai Road", landmark: "State Highway 96 Corridor", pincode: "638009" },
    { name: "Poondurai Road", landmark: "Poondurai Highway Junction", pincode: "638002" },
    { name: "Muthampalayam", landmark: "Near TNHB Housing Colony", pincode: "638009" },
    { name: "Muthampalayam Housing Unit", landmark: "Phase 1 & Phase 2 Enclave", pincode: "638009" },
    { name: "Lakkapuram", landmark: "Near Lakkapuram Checkpost", pincode: "638002" },
    { name: "46 Pudur", landmark: "Near Pudur Panchayat Board", pincode: "638002" },
    { name: "Transport Nagar", landmark: "Lorry Owners Association Ground", pincode: "638002" },
    { name: "Nadarmedu", landmark: "Near Nadarmedu Railway Gate", pincode: "638002" },
    { name: "Vendipalayam", landmark: "Near Vendipalayam Railway Track", pincode: "638002" },
    { name: "Karumandisellipalayam South", landmark: "Near South Bypass Ring", pincode: "638052" },
    { name: "Modakkurichi", landmark: "Modakkurichi Taluk Headquarters", pincode: "638104" },
    { name: "Modakkurichi Road", landmark: "State Highway Southern Link", pincode: "638104" },
    { name: "Sivagiri Road", landmark: "Southern Agricultural Corridor", pincode: "638109" },
    { name: "Ganapathipalayam", landmark: "Near South Textile Processing Mills", pincode: "638153" },
    { name: "Jaycees School Area", landmark: "Near Jaycees Matriculation School", pincode: "638002" },
    { name: "Rangampalayam", landmark: "Near Arts College Road", pincode: "638009" },
    { name: "Sakthi Nagar South", landmark: "Near Surampatti Extension", pincode: "638009" },
    { name: "Anandha Nagar", landmark: "Near Kollampalayam Bypass", pincode: "638002" },
    { name: "Periyar Nagar South", landmark: "Near South Overbridge", pincode: "638001" },
    { name: "Marapalam South", landmark: "Canal Link Road", pincode: "638001" },
    { name: "Shastri Nagar", landmark: "Behind Railway Colony", pincode: "638002" },
    { name: "Teachers Nagar Kasipalayam", landmark: "Residential Layout Phase 3", pincode: "638009" },
    { name: "Soolai", landmark: "Near Soolai Bus Stop", pincode: "638004" },
    { name: "Soolai Medu", landmark: "Soolai High Grounds", pincode: "638004" },
    { name: "Kollampalayam Bypass", landmark: "Near Ring Road Flyover", pincode: "638002" },
    { name: "Railway Colony South", landmark: "Railway Officers Quarters", pincode: "638002" },
    { name: "Municipal Colony South", landmark: "Near Park Enclave", pincode: "638004" },
    { name: "SKC Road", landmark: "Textile Market Road South", pincode: "638009" },
    { name: "Muthuvelappa Street", landmark: "Near Surampatti Bazaar", pincode: "638009" },
    { name: "Velli Thiruppur Road", landmark: "Rural Southern Cross", pincode: "638314" },
    { name: "Pasur Road", landmark: "Cauvery South Riverbank Road", pincode: "638154" },
    { name: "Avalpoondurai", landmark: "Near Avalpoondurai Temple", pincode: "638115" },
    { name: "Vellode", landmark: "Near Vellode Bird Sanctuary Road", pincode: "638112" },
    { name: "Chennimalai Town", landmark: "Handloom Weavers Capital", pincode: "638051" },
    { name: "Chennimalai Murugan Temple Foothills", landmark: "Temple Foothills Arch", pincode: "638051" },
    { name: "Kodumudi Bypass", landmark: "Near Magudeshwarar Temple Highway", pincode: "638151" },
    { name: "Unjalur Road", landmark: "Cauvery Basin Belt", pincode: "638152" },
    { name: "Vadivullamangalam", landmark: "Near South Canal Bank", pincode: "638112" },
    { name: "Arachalur", landmark: "Historic Rock Caves Road", pincode: "638101" },
    { name: "Nathakadaiyur Road", landmark: "Link to Kangeyam Highway", pincode: "638108" },
    { name: "Nallampatti", landmark: "Near Rural Processing Mills", pincode: "638057" }
  ]
};
